import { FXGraphNode } from "../FXGraphNode";
import type { FXCompilerContext, FXValueParamHandle } from "../compiler/FXCompilerContext";
import { FXCompilerErrorException } from "../compiler/FXCompilerError";
import type { FXExpr } from "../ir/FXExpr";
import * as fxExprBuilders from "../ir/FXExprBuilder";
import type { FXExprBuilderApi } from "../ir/FXExprBuilder";
import type { FXSocketDescriptor } from "../socket/FXSocket";
import type { FXGLSLTypeName, FXValueType } from "../socket/FXValueType";
import { FX_VALUE_TYPES, resolveValueType } from "../socket/FXValueType";
import type { FXCurveData, FXGradientData, FXParamSpec } from "./FXParamSpec";
import { finiteScalar, finiteScalarOrVector, finiteVector } from "./paramValidators.Internal";
import type { FXBehaviorPhaseName, FXNodeCost, FXRenderStageName } from "./defineNode";
import type { FXSocketSpec } from "./FXSocketSpec";
import { isTargetInputDefault, toSocketDescriptors } from "./socketDescriptors.Internal";

/** An {@link FXSocketSpec} known (by construction) to carry an editable inline default. */
type FXEditableSocketSpec = FXSocketSpec & { readonly value: number | readonly number[] };

// Public types living in the sibling `defineNode.ts`, re-exported so internal
// consumers keep importing them alongside the impl.
export type { FXBehaviorPhaseName, FXNodeBackend, FXRenderStageName } from "./defineNode";

export type { FXExprBuilderApi } from "../ir/FXExprBuilder";

/**
 * The narrowest type a node's generic `T` may resolve to - `float` if its constraint allows
 * it, else the constraint's first entry. Used to evaluate a cost function at its cheapest
 * representative case when no real graph resolution is available.
 */
export function narrowestGenericType(
  constraint: readonly FXGLSLTypeName[] | undefined,
): FXValueType {
  if (constraint === undefined || constraint.includes("float")) {
    return FX_VALUE_TYPES.float;
  }
  const first = constraint[0];
  if (first === undefined) {
    throw new Error("narrowestGenericType: generic constraint must list at least one type");
  }
  return FX_VALUE_TYPES[first];
}

/** Shape of the user `build` callback captured from the descriptor. */
export interface FXDescriptorBuildArgs {
  readonly inputs: Record<string, FXExpr>;
  readonly params: Record<string, FXExpr | string | boolean>;
  /** The node's resolved generic type `T` (only meaningful for a generic node). */
  readonly resolvedT: FXValueType;
  readonly target: { read: (name: string) => FXExpr };
  /** Materializes a shared sub-expression into an SSA local (see {@link FXCompilerContext.defineLocal}). */
  readonly local: (hint: string, expr: FXExpr) => FXExpr;
  /** Emits a deduplicated helper (escape hatch for JS-only helpers used by a single node). */
  readonly emitHelper: (key: string, source: string) => void;
  readonly fn: FXExprBuilderApi;
}
export type FXDescriptorBuild = (args: FXDescriptorBuildArgs) => Record<string, FXExpr>;

/** Everything the wrapper needs from a descriptor, pre-normalized by `defineNode`. */
export interface FXDescriptorCore {
  readonly type: string;
  readonly domain: "render" | "behavior" | "shared";
  readonly stage?: FXRenderStageName | "param";
  readonly phase?: FXBehaviorPhaseName | "param";
  /** Behavior: a fixed `phase` is only a default, overridable by graph placement. */
  readonly phaseFlexible?: boolean;
  /** Constraint of the node's generic `T`, present iff any socket is typed `"T"`. */
  readonly constraint?: readonly FXGLSLTypeName[];
  readonly inputSpecs: Readonly<Record<string, FXSocketSpec>>;
  readonly outputSpecs: Readonly<Record<string, FXSocketSpec>>;
  readonly params: Readonly<Record<string, FXParamSpec>>;
  /** Explicit target-input reads (input-default reads are derived separately). */
  readonly reads?:
    readonly string[] | ((params: Readonly<Record<string, unknown>>) => readonly string[]);
  /** Lighting intrinsic this node emits, surfaced through {@link FXGraphNode.lightingIntrinsic}. */
  readonly lightingIntrinsic?: string;
  /** Complexity estimate, surfaced through {@link FXGraphNode.estimateCost}. */
  readonly cost: FXNodeCost;
  readonly build: FXDescriptorBuild;
  /** Render-only baseline (WebGL1) fallback; see {@link FXNodeDescriptor.baselineBuild}. */
  readonly baselineBuild?: FXDescriptorBuild;
}

/**
 * Wrapper node generated by {@link defineNode}: holds resolved param values as plain data
 * and derives `applyParams`/`syncLiveValues`/`cacheKey`/`build` mechanically from the descriptor.
 */
export class FXDescriptorNode extends FXGraphNode {
  public readonly type: string;
  public readonly inputs: readonly FXSocketDescriptor[];
  public readonly outputs: readonly FXSocketDescriptor[];

  private readonly core: FXDescriptorCore;
  /** Current literal values for every parameter, keyed by name (defaults + applied). */
  private readonly values = new Map<
    string,
    number | readonly number[] | string | boolean | FXCurveData | FXGradientData
  >();
  /** Structural param names in declaration order - the deterministic cacheKey basis. */
  private readonly structuralKeys: readonly string[];
  /**
   * Input sockets carrying an editable inline default (`value`), as [key, specification]
   * pairs in declaration order. Their override lives in {@link values} keyed by socket key;
   * `build` bakes it as an IR literal when unconnected, and it participates in {@link cacheKey}
   * (editing recompiles).
   */
  private readonly editableInputs: readonly (readonly [string, FXEditableSocketSpec])[];
  /** Target inputs read via an input socket's `targetInput` default (static). */
  private readonly inputDefaultReads: readonly string[];
  /** Live handles retained from the last build, keyed by value-param name. */
  private readonly liveHandles = new Map<string, FXValueParamHandle>();

  private stageValue: FXRenderStageName;
  private phaseValue: FXBehaviorPhaseName;
  /** Whether any socket is generic (`"T"`) - gates the `resolvedType` lookup in `build`. */
  private readonly isGeneric: boolean;
  /** Name of the structural `valueType` param that annotates `T` (a source's hint), if any. */
  private readonly genericHintKey: string | undefined;

  constructor(core: FXDescriptorCore, parameters?: Readonly<Record<string, unknown>>) {
    super();
    this.core = core;
    this.type = core.type;
    this.inputs = toSocketDescriptors(core.inputSpecs, core.constraint);
    this.outputs = toSocketDescriptors(core.outputSpecs, core.constraint);
    this.isGeneric = core.constraint !== undefined;
    this.genericHintKey = Object.entries(core.params).find(
      ([, specification]) =>
        specification.kind === "structural" && specification.type === "valueType",
    )?.[0];
    this.structuralKeys = Object.entries(core.params)
      .filter(([, specification]) => specification.kind === "structural")
      .map(([name]) => name);
    this.editableInputs = Object.entries(core.inputSpecs).filter(
      (entry): entry is [string, FXEditableSocketSpec] => entry[1].value !== undefined,
    );
    this.inputDefaultReads = Object.values(core.inputSpecs)
      .map((specification) => specification.default)
      .filter(isTargetInputDefault)
      .map((targetInputDefault) => targetInputDefault.targetInput);

    for (const [name, specification] of Object.entries(core.params)) {
      this.values.set(name, specification.default);
    }
    // Seed each editable input's override to its declared inline default; an absent
    // override in a snapshot resets to this (mirrors the value-param reset rule below).
    for (const [key, specification] of this.editableInputs) {
      this.values.set(key, specification.value);
    }

    this.stageValue = core.stage === undefined || core.stage === "param" ? "fragment" : core.stage;
    this.phaseValue = core.phase === undefined || core.phase === "param" ? "update" : core.phase;

    if (parameters !== undefined) {
      this.applyParams(parameters);
    }
  }

  /** GLSL stage (render backend). Present for structural compatibility with `FXRenderNode`. */
  public get stage(): FXRenderStageName {
    return this.stageValue;
  }

  /** Behavior phase (behavior backend). Present for structural compatibility with `FXBehaviorNode`. */
  public get phase(): FXBehaviorPhaseName {
    return this.phaseValue;
  }

  /** A `stage: "param"` node has no intrinsic stage - the compiler infers it (render). */
  public get stageFlexible(): boolean {
    return this.core.stage === "param";
  }

  /**
   * A `phase: "param"` node has no intrinsic phase; a `phaseFlexible` node keeps its declared
   * `phase` as a default but lets graph placement override it (see `resolvePlacementPhases`).
   */
  public get phaseFlexible(): boolean {
    return this.core.phase === "param" || this.core.phaseFlexible === true;
  }

  /** Builtins this node may read: the descriptor's `reads` unioned with every input socket's `targetInput` default. */
  public override get targetReads(): readonly string[] {
    const declared =
      typeof this.core.reads === "function"
        ? this.core.reads(Object.fromEntries(this.values))
        : (this.core.reads ?? []);
    return [...new Set<string>([...declared, ...this.inputDefaultReads])];
  }

  public override get lightingIntrinsic(): string | undefined {
    return this.core.lightingIntrinsic;
  }

  /**
   * Static complexity estimate (see {@link FXGraphNode.estimateCost}): the descriptor's cost
   * function evaluated against current *param* values only (never a pin's editable-input
   * value - it doesn't change what code runs) and the resolved `T`, falling back to
   * {@link narrowestGenericType} when the caller doesn't know the graph-resolved width.
   */
  public override estimateCost(resolvedT?: FXValueType): number {
    if (typeof this.core.cost === "number") {
      return this.core.cost;
    }
    const parameters: Record<string, unknown> = {};
    for (const name of Object.keys(this.core.params)) {
      parameters[name] = this.values.get(name);
    }
    const type =
      resolvedT ??
      (this.isGeneric ? narrowestGenericType(this.core.constraint) : FX_VALUE_TYPES.float);
    return this.core.cost({ params: parameters, resolvedT: type });
  }

  public override resolveGenericHint(): FXGLSLTypeName | undefined {
    if (this.genericHintKey === undefined) {
      return undefined;
    }
    // A `valueType` param may store the UI-only `"color"` alias; the engine resolves it to
    // `vec4` (color == vec4). Every other value is already a concrete GLSL type.
    const stored = this.values.get(this.genericHintKey);
    return (stored === "color" ? "vec4" : stored) as FXGLSLTypeName;
  }

  public override applyParams(parameters: Readonly<Record<string, unknown>>): void {
    // Apply the generic annotation (`valueType`) first, so a `generic` value param
    // coerces against the up-to-date width in the same pass.
    if (this.genericHintKey !== undefined && parameters[this.genericHintKey] !== undefined) {
      const specification = this.core.params[this.genericHintKey];
      if (specification === undefined) {
        throw new Error("FXDescriptorNode: generic hint key must reference a declared param");
      }
      this.values.set(
        this.genericHintKey,
        this.coerce(this.genericHintKey, specification, parameters[this.genericHintKey]),
      );
    }
    for (const [name, specification] of Object.entries(this.core.params)) {
      if (name === this.genericHintKey) {
        continue;
      }
      const raw = parameters[name];
      if (raw !== undefined) {
        this.values.set(name, this.coerce(name, specification, raw));
      } else if (specification.kind === "value" && specification.type === "generic") {
        // The type annotation may have changed without a new value - keep the stored
        // value's width consistent with the (possibly new) generic width.
        this.values.set(name, this.reshapeGenericValue(this.values.get(name)));
      } else if (specification.kind === "value") {
        // A value param absent from this snapshot resets to its declared default, so a
        // "reset to default" serialized as key removal doesn't strand the last-shown value.
        this.values.set(name, specification.default);
      }
    }
    // Editable input overrides ride the same params bag, keyed by socket key. An absent
    // one resets to the declared inline default; a generic seed keeps its width in step
    // with the type param applied above.
    for (const [key, specification] of this.editableInputs) {
      const raw = parameters[key];
      if (raw !== undefined) {
        this.values.set(key, this.coerceSocketValue(key, specification, raw));
      } else if (specification.type === "T") {
        this.values.set(key, this.reshapeGenericValue(this.values.get(key)));
      } else {
        this.values.set(key, specification.value);
      }
    }
    if (this.core.stage === "param") {
      const raw = parameters["stage"];
      if (raw !== undefined) {
        this.stageValue = this.coerceStage(raw);
      }
    }
    if (this.core.phase === "param") {
      const raw = parameters["phase"];
      if (raw !== undefined) {
        this.phaseValue = this.coercePhase(raw);
      }
    }
  }

  public override syncLiveValues(): void {
    for (const [name, handle] of this.liveHandles) {
      handle.update(this.values.get(name) as number | readonly number[]);
    }
  }

  public override cacheKey(): string {
    // JSON-encode the [name, value] pairs: a plain `name=value` join on `:` would let an
    // enum option containing `:`/`=` collide with a different structural set. Editable
    // input defaults are baked as inline literals so they must also be in the hash;
    // tagged `s`/`i` so a structural param and an input socket sharing a name hash distinctly.
    const parts: (readonly [string, string, unknown])[] = [
      ...this.structuralKeys.map((name) => ["s", name, this.values.get(name)] as const),
      ...this.editableInputs.map(([key]) => ["i", key, this.values.get(key)] as const),
    ];
    // A flexible node's stage/phase placement is inferred by the compiler and folded into
    // the structural hash there instead (render `stageTag`; behavior `nodeKey`).
    return JSON.stringify(parts);
  }

  public build(context: FXCompilerContext): void {
    this.runBuild(context, this.core.build);
  }

  /**
   * Render-only baseline (WebGL1) build: prefers `core.baselineBuild` when the descriptor supplied
   * one, else runs the same primary `build` {@link build} would - so a node with no baselineBuild
   * compiles identically under both compilers, and only a node that declared one ever diverges.
   * `FXCompilerStandard` never calls this method.
   */
  public override baselineBuild(context: FXCompilerContext): void {
    this.runBuild(context, this.core.baselineBuild ?? this.core.build);
  }

  private runBuild(context: FXCompilerContext, build: FXDescriptorBuild): void {
    this.liveHandles.clear();

    // A generic node sizes its value params and output from the resolved `T`.
    const resolvedT = this.isGeneric ? context.resolvedType() : FX_VALUE_TYPES.float;

    const inputs: Record<string, FXExpr> = {};
    for (const [key, specification] of Object.entries(this.core.inputSpecs)) {
      if (context.hasInput(key)) {
        inputs[key] = context.readInput(key);
      } else if (specification.value !== undefined) {
        // Unconnected editable input: bake the live override as an inline IR literal
        // (no uniform/binding - a fixed value never spends a slot; only param nodes do).
        inputs[key] = this.editableInputLiteral(key, specification, resolvedT);
      } else {
        const fallback = this.resolveDefault(specification.default, context);
        if (fallback !== undefined) {
          inputs[key] = fallback;
        }
      }
    }

    const parameters: Record<string, FXExpr | string | boolean> = {};
    for (const [name, specification] of Object.entries(this.core.params)) {
      parameters[name] =
        specification.kind === "structural"
          ? (this.values.get(name) as string | boolean)
          : this.allocateValueParam(context, name, specification, resolvedT);
    }

    const outputs = build({
      inputs,
      params: parameters,
      resolvedT,
      target: { read: (name) => context.readTargetInput(name) },
      local: (hint, expr) => context.defineLocal(hint, expr),
      emitHelper: (key, source) => context.emitHelper(key, source),
      fn: context.builders,
    });

    for (const [key, expr] of Object.entries(outputs)) {
      context.setOutput(key, expr);
    }
  }

  /** Reshapes a `generic` value param to the node's current generic width, padding with 0. */
  private reshapeGenericValue(value: unknown): number | readonly number[] {
    const width = this.currentGenericWidth();
    const source =
      typeof value === "number" ? [value] : ((value as readonly number[] | undefined) ?? []);
    if (width === 1) {
      return source[0] ?? 0;
    }
    const output = new Array<number>(width).fill(0);
    for (let i = 0; i < width && i < source.length; i++) {
      // In-bounds by the loop guard; `?? 0` only matches the array's own pre-fill value.
      output[i] = source[i] ?? 0;
    }
    return output;
  }

  /** Component width the node's generic value param currently carries (from its annotation). */
  private currentGenericWidth(): number {
    const hint = this.resolveGenericHint();
    return hint === undefined ? 1 : resolveValueType(hint).components;
  }

  private resolveDefault(
    value: FXSocketSpec["default"],
    context: FXCompilerContext,
  ): FXExpr | undefined {
    if (value === undefined) {
      return undefined;
    }
    if (isTargetInputDefault(value)) {
      return context.readTargetInput(value.targetInput);
    }
    return value;
  }

  private allocateValueParam(
    context: FXCompilerContext,
    name: string,
    specification: Extract<FXParamSpec, { kind: "value" }>,
    resolvedT: FXValueType,
  ): FXExpr {
    // `generic` params size to the resolved `T`; concrete params to their declared type. The
    // backend context owns the uniform-vs-binding ABI behind allocateValueParam; the node just
    // retains the returned handle for syncLiveValues.
    const type =
      specification.type === "generic" ? resolvedT : resolveValueType(specification.type);
    const value = this.values.get(name) as number | readonly number[];
    const valueParam = context.allocateValueParam(type, value, name);
    this.liveHandles.set(name, valueParam.handle);
    return valueParam.expr;
  }

  /**
   * Coerces a raw editable-input override to the socket's value type (a generic `"T"`
   * socket's width follows the sibling `valueType` param). A scalar enforces `min`/`max`,
   * rejecting a runaway snapshot value as `bad-param`; on a vector they stay editor hints.
   */
  private coerceSocketValue(
    key: string,
    specification: FXSocketSpec,
    raw: unknown,
  ): number | readonly number[] {
    const where = `${this.type}.${key}`;
    if (specification.type === "T" && this.genericHintKey === undefined) {
      // No structural `valueType` param to size against - accept whatever shape the editor
      // sends (it already knows the resolved width from the graph); see `finiteScalarOrVector`.
      return finiteScalarOrVector(where, raw);
    }
    const width =
      specification.type === "T"
        ? this.currentGenericWidth()
        : resolveValueType(specification.type).components;
    return width === 1
      ? finiteScalar(where, raw, specification.min, specification.max)
      : finiteVector(where, raw, width);
  }

  /** Bakes an unconnected editable input's live override as an inline IR literal (no slot). */
  private editableInputLiteral(
    key: string,
    specification: FXSocketSpec,
    resolvedT: FXValueType,
  ): FXExpr {
    const type = specification.type === "T" ? resolvedT : resolveValueType(specification.type);
    const value = this.values.get(key);
    if (type.components === 1) {
      return fxExprBuilders.lit(
        typeof value === "number" ? value : ((value as readonly number[])[0] ?? 0),
      );
    }
    const source = Array.isArray(value) ? value : [value as number];
    const components = Array.from({ length: type.components }, (_, index) => source[index] ?? 0);
    return fxExprBuilders.litVec(...components);
  }

  private coerce(
    name: string,
    specification: FXParamSpec,
    raw: unknown,
  ): number | readonly number[] | string | boolean | FXCurveData | FXGradientData {
    const where = `${this.type}.${name}`;
    switch (specification.type) {
      case "float":
        return finiteScalar(where, raw, specification.min, specification.max);
      case "vec2":
      case "vec3":
      case "vec4": {
        // Width comes from the declared type, not the default's length - a mismatch is
        // rejected at define time, but deriving it here keeps coerce correct anyway.
        const expected = specification.type === "vec2" ? 2 : specification.type === "vec3" ? 3 : 4;
        return finiteVector(where, raw, expected);
      }
      case "generic": {
        const width = this.currentGenericWidth();
        return width === 1 ? finiteScalar(where, raw) : finiteVector(where, raw, width);
      }
      case "curve": {
        // `typeof null === "object"` too; `!raw` excludes exactly that case without writing
        // the banned null literal (raw is untrusted serialized input, so this really can be
        // null here, not just undefined).
        if (typeof raw !== "object" || !raw || !Array.isArray((raw as FXCurveData).points)) {
          throw new FXCompilerErrorException({
            code: "bad-curve-value",
            message: `FXNodeDefinition: ${where} expects a curve ({ points: [...] })`,
            params: { where },
          });
        }
        // Untrusted serialized input: a `{ position: "x" }` anchor would otherwise bake
        // a NaN into the LUT silently, corrupting the scale/value it drives.
        for (const point of (raw as { points: readonly unknown[] }).points) {
          // `typeof null === "object"` too; `!point` excludes exactly that case without
          // writing the banned null literal (point is untrusted serialized input, so this
          // really can be null here, not just undefined).
          if (typeof point !== "object" || !point) {
            throw new FXCompilerErrorException({
              code: "bad-curve-point",
              message: `FXNodeDefinition: ${where} expects curve points of finite { position, value } numbers`,
              params: { where },
            });
          }
          const anchor = point as {
            position?: unknown;
            value?: unknown;
            interpolation?: unknown;
          };
          if (
            typeof anchor.position !== "number" ||
            !Number.isFinite(anchor.position) ||
            typeof anchor.value !== "number" ||
            !Number.isFinite(anchor.value)
          ) {
            throw new FXCompilerErrorException({
              code: "bad-curve-point",
              message: `FXNodeDefinition: ${where} expects curve points of finite { position, value } numbers`,
              params: { where },
            });
          }
          // Optional per-point smoothing mode (inline curve only; the LUT baker ignores it).
          if (
            anchor.interpolation !== undefined &&
            anchor.interpolation !== "smooth" &&
            anchor.interpolation !== "sharp"
          ) {
            throw new FXCompilerErrorException({
              code: "bad-curve-interpolation",
              message: `FXNodeDefinition: ${where} curve point interpolation must be "smooth" or "sharp"`,
              params: { where },
            });
          }
        }
        return raw as FXCurveData;
      }
      case "gradient": {
        const stops = (raw as FXGradientData | undefined)?.stops;
        // `typeof null === "object"` too; `!raw` excludes exactly that case without writing
        // the banned null literal (raw is untrusted serialized input, so this really can be
        // null here, not just undefined).
        if (typeof raw !== "object" || !raw || !Array.isArray(stops)) {
          throw new FXCompilerErrorException({
            code: "bad-gradient-value",
            message: `FXNodeDefinition: ${where} expects a gradient ({ stops: [...] })`,
            params: { where },
          });
        }
        if (stops.length === 0) {
          throw new FXCompilerErrorException({
            code: "empty-gradient",
            message: `FXNodeDefinition: ${where} expects at least one gradient stop`,
            params: { where },
          });
        }
        // Untrusted serialized input: validate every stop's position and 4-channel RGBA are
        // finite, so a malformed stop can't bake a NaN color into the emitted mix chain.
        for (const stop of stops as readonly unknown[]) {
          // `typeof null === "object"` too; `!stop` excludes exactly that case without
          // writing the banned null literal (stop is untrusted serialized input, so this
          // really can be null here, not just undefined).
          if (typeof stop !== "object" || !stop) {
            throw new FXCompilerErrorException({
              code: "bad-gradient-stop",
              message: `FXNodeDefinition: ${where} expects stops of { position: number, color: [r,g,b,a] }`,
              params: { where },
            });
          }
          const stopCandidate = stop as { position?: unknown; color?: unknown };
          if (
            typeof stopCandidate.position !== "number" ||
            !Number.isFinite(stopCandidate.position) ||
            !Array.isArray(stopCandidate.color) ||
            stopCandidate.color.length !== 4 ||
            !stopCandidate.color.every(
              (component) => typeof component === "number" && Number.isFinite(component),
            )
          ) {
            throw new FXCompilerErrorException({
              code: "bad-gradient-stop",
              message: `FXNodeDefinition: ${where} expects stops of { position: number, color: [r,g,b,a] }`,
              params: { where },
            });
          }
        }
        return raw as FXGradientData;
      }
      case "enum": {
        if (typeof raw !== "string" || !specification.options.includes(raw)) {
          const options = specification.options.join(", ");
          throw new FXCompilerErrorException({
            code: "bad-enum-value",
            message: `FXNodeDefinition: ${where} expects one of [${options}]`,
            params: { where, options },
          });
        }
        return raw;
      }
      case "flag": {
        if (typeof raw !== "boolean") {
          throw new FXCompilerErrorException({
            code: "bad-flag-value",
            message: `FXNodeDefinition: ${where} expects a boolean`,
            params: { where },
          });
        }
        return raw;
      }
      case "valueType": {
        // `"color"` is a UI alias for `vec4`. A node offering it in `options` (e.g. `constant`)
        // stores it as-is; one that doesn't maps a stale/aliased value to `vec4` so old projects load.
        const declaredOptions = specification.options as readonly string[];
        const value = raw === "color" && !declaredOptions.includes("color") ? "vec4" : raw;
        if (typeof value !== "string" || !declaredOptions.includes(value)) {
          const options = declaredOptions.join(", ");
          throw new FXCompilerErrorException({
            code: "bad-enum-value",
            message: `FXNodeDefinition: ${where} expects one of [${options}]`,
            params: { where, options },
          });
        }
        return value;
      }
    }
  }

  private coerceStage(raw: unknown): FXRenderStageName {
    if (raw !== "vertex" && raw !== "fragment") {
      throw new FXCompilerErrorException({
        code: "bad-node-stage",
        message: `FXNodeDefinition: ${this.type}.stage expects "vertex" | "fragment"`,
        params: { type: this.type },
      });
    }
    return raw;
  }

  private coercePhase(raw: unknown): FXBehaviorPhaseName {
    if (raw !== "spawn" && raw !== "update") {
      throw new FXCompilerErrorException({
        code: "bad-node-phase",
        message: `FXNodeDefinition: ${this.type}.phase expects "spawn" | "update"`,
        params: { type: this.type },
      });
    }
    return raw;
  }
}
